### ISSUE TITLE
Uncaught TypeError: Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by GabLeRoux** [tcarlsen/atom-jsonlint#1]
### steps to reproduce

I Linted the file just before using Json: prettify
Hit enter, `cmd+z`
Saved document (it's a 4071 lines document)
Saved file.
Closed tab and issue happened. Does the same when I switch from a tab to another.

Not quite sure it does this everytime, everything went fine other then that (document was saved, did't really want to lint it in fact, but said `No errors were found!` at the JSON Lint report section). Had issue again when closing a linted document.

Hope it helps find the issue ;)

**Atom Version**: 0.177.0
**System**: Mac OS X 10.10.2
**Thrown From**: [jsonlint](https://github.com/tcarlsen/atom-jsonlint) package, v1.0.1
### Stack Trace

Uncaught TypeError: Cannot read property 'data' of undefined

```
At /Users/gableroux/.atom/packages/jsonlint/node_modules/atom-message-panel/lib/MessagePanelView.js:206

TypeError: Cannot read property 'data' of undefined
  at [object Object].MessagePanelView.resizeStopped (/Users/gableroux/.atom/packages/jsonlint/node_modules/atom-message-panel/lib/MessagePanelView.js:206:6)
  at [object Object].MessagePanelView.close (/Users/gableroux/.atom/packages/jsonlint/node_modules/atom-message-panel/lib/MessagePanelView.js:108:12)
  at /Users/gableroux/.atom/packages/jsonlint/lib/linter.coffee:40:14
  at Emitter.module.exports.Emitter.emit (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/pane-container.js:347:34
  at Emitter.module.exports.Emitter.emit (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.setActiveItem (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/pane.js:264:22)
  at Pane.module.exports.Pane.activateItem (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/pane.js:328:21)
  at tabs-tab.<anonymous> (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/tabs/lib/tab-bar-view.js:184:24)
  at space-pen-ul.jQuery.event.dispatch (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:4430:9)
  at space-pen-ul.elemData.handle (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:4116:28)

```
### Commands

```
     -0:35.4 core:move-left (ol.results-view.list-tree.focusable-panel.has-collapsable-children)
  7x -0:35.0 core:move-up (ol.results-view.list-tree.focusable-panel.has-collapsable-children)
     -0:20.6 command-palette:toggle (atom-text-editor.editor)
     -0:17.9 core:confirm (atom-text-editor.editor.mini)
     -0:17.9 jsonlint:lint (atom-text-editor.editor)
     -0:16.4 command-palette:toggle (atom-text-editor.editor)
     -0:15.1 core:move-down (atom-text-editor.editor.mini)
     -0:14.7 core:confirm (atom-text-editor.editor.mini)
     -0:14.6 pretty-json:prettify (atom-text-editor.editor)
     -0:13.7 refactor:done (atom-text-editor.editor)
     -0:13.7 editor:newline (atom-text-editor.editor)
     -0:12.8 core:undo (atom-text-editor.editor)
     -0:09.6 find-and-replace:show (atom-text-editor.editor)
     -0:09.0 core:confirm (atom-text-editor.editor.mini)
     -0:06.3 pane:show-previous-item (atom-text-editor.editor.mini)
     -0:03.1 core:save (atom-text-editor.editor.mini)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "metrics",
      "timecop",
      "vim-mode",
      "symfony-snippets",
      "atom-compile-coffee"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
ScssBundle, v0.4.0
angularjs, v0.1.0
ascii-codes, v0.3.3
atom-beautify, v0.21.3
atom-django, v0.2.0
autocomplete-plus, v2.1.5
build, v0.23.4
coffee-lint, v0.7.3
coffee-refactor, v0.6.2
color-picker, v1.4.4
css-snippets, v0.5.0
editorconfig, v0.3.0
grunt-runner, v0.6.0
js-refactor, v0.3.0
jsonlint, v1.0.1
language-blade, v0.7.0
language-erlang, v2.0.0
language-gitignore, v0.1.1
language-ini, v1.3.0
language-python-django-templates, v0.1.0
laravel, v0.4.2
laravel-facades, v1.0.0
linter, v0.11.1
linter-pylint, v0.2.0
linter-scss-lint, v0.0.11
linter-xmllint, v0.0.5
minimap, v4.1.4
minimap-git-diff, v3.1.1
pretty-json, v0.3.2
refactor, v0.4.1
scope-inspector, v0.2.1
ssh-config, v0.10.0
travis-ci-status, v0.11.2

# Dev
No dev packages
```

/cc @atom/core

**Comment by Galan2X** [comment]
I get the same crash on every save of a .json file or leaving the tab of a .json file. The linting itself seems to work fine.

**Comment by tcarlsen** [comment]
Thx for reporting this. I will look into the problem on Monday. (on vacation atm)

—

**Comment by tcarlsen** [comment]
this was a problem in AMP (https://github.com/tcarlsen/atom-message-panel/issues/65) and has been fixed now. I believe you have to reinstall jsonlint fto force atom to update its dependencies

**Comment by GabLeRoux** [comment]
`apm install jsonlint -f` seems to do the trick, thanks :)
