### ISSUE TITLE
Failed to activate the jsonlint package

### ISSUE THREAD

**Issue by DroidCoder** [tcarlsen/atom-jsonlint#2]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.187.0
**System**: Mac OS X 10.10.2
**Thrown From**: [jsonlint](https://github.com/tcarlsen/atom-jsonlint) package, v1.0.1
### Stack Trace

Failed to activate the jsonlint package

```
At Cannot read property 'buffer' of undefined

TypeError: Cannot read property 'buffer' of undefined
  at /Users/athanasioskarpouzis/.atom/packages/jsonlint/lib/main.coffee:14:14
  at Config.module.exports.Config.observeKeyPath (/Applications/Atom.app/Contents/Resources/app/src/config.js:621:7)
  at Config.module.exports.Config.observe (/Applications/Atom.app/Contents/Resources/app/src/config.js:133:21)
  at Object.module.exports.activate (/Users/athanasioskarpouzis/.atom/packages/jsonlint/lib/main.coffee:12:17)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:240:19)
  at /Applications/Atom.app/Contents/Resources/app/src/package.js:221:30
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:167:15)
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:214:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:465:21)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:226:29
  at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:63:47)
  at /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:70:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:150:18)
  at Socket.emit (events.js:138:20)
  at Pipe.close (net.js:477:12)

```
### Commands

```
     -0:20.3 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
jsonlint, v1.0.1
language-gradle, v0.0.3
pretty-json, v0.3.2

# Dev
No dev packages
```

**Comment by tcarlsen** [comment]
cannot reproduce ... Try uninstall the packages and reinstall
