### ISSUE TITLE
Uncaught TypeError: Arguments to path.resolve must be strings

### ISSUE THREAD

**Issue by brainlid** [tcarlsen/atom-jsonlint#8]
## Steps to reproduce

Copy some JSON that has an error like this... (trailing comma ',')

``` json
{
  "something": "nice",
}
```

Paste it into Atom editor in a new tab. Change file language to "JSON". Run "Jsonlint: lint" (via ctrl+shift+p for me on Linux).

It correctly shows the error. Clicking on the error description/display raises and exception.
## Problem explanation

The file is unsaved. When the file is saved, it works correctly.

When manually editing or reviewing JSON, it would be nice if it didn't require the file to be saved to properly locate/display the error.
## Exception Details

**Atom Version**: 1.0.7
**System**: Ubuntu 14.04.3
**Thrown From**: [jsonlint](https://github.com/tcarlsen/atom-jsonlint) package, v1.1.2
### Stack Trace

Uncaught TypeError: Arguments to path.resolve must be strings

```
At path.js:400

TypeError: Arguments to path.resolve must be strings
  at Object.posix.resolve (path.js:400:13)
  at Object.posix.relative (path.js:467:14)
  at [object Object].LineMessageView.goToLine (/home/mark/.atom/packages/jsonlint/node_modules/atom-message-panel/lib/LineMessageView.js:51:23)
  at HTMLPreElement.<anonymous> (/home/mark/.atom/packages/jsonlint/node_modules/atom-message-panel/node_modules/space-pen/lib/space-pen.js:214:36)
  at HTMLPreElement.jQuery.event.dispatch (/home/mark/.atom/packages/jsonlint/node_modules/atom-message-panel/node_modules/space-pen/vendor/jquery.js:4676:9)
  at HTMLPreElement.elemData.handle (/home/mark/.atom/packages/jsonlint/node_modules/atom-message-panel/node_modules/space-pen/vendor/jquery.js:4360:46)

```
### Commands

```
     -1:41.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:39.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:39.8.0 jsonlint:lint (a.inline-block)
     -0:53.7.0 application:new-file (atom-text-editor.editor.is-focused)
     -0:53 core:paste (atom-text-editor.editor.is-focused)
     -0:46.4.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:43.4.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:43 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:43 jsonlint:lint (atom-text-editor.editor)
     -0:13 application:new-file (atom-text-editor.editor.is-focused)
     -0:12 core:paste (atom-text-editor.editor.is-focused)
     -0:08.9.0 grammar-selector:show (atom-text-editor.editor)
     -0:07.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:06.0 command-palette:toggle (a.inline-block)
     -0:02.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:02.8.0 jsonlint:lint (a.inline-block)
```

**Comment by tcarlsen** [comment]
This is a "issue" in [atom-message-panel](https://github.com/tcarlsen/atom-message-panel)

issue created over there: https://github.com/tcarlsen/atom-message-panel/issues/77
