### ISSUE TITLE
Uncaught TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by vgonzalezr** [tcarlsen/atom-jsonlint#9]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.2.3
**System**: Ubuntu 14.04.3
**Thrown From**: [jsonlint](https://github.com/tcarlsen/atom-jsonlint) package, v1.1.2
### Stack Trace

Uncaught TypeError: Path must be a string. Received undefined

```
At path.js:8

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:8:11)
    at Object.posix.relative (path.js:494:3)
    at [object Object].LineMessageView.goToLine (/home/victor/.atom/packages/jsonlint/node_modules/atom-message-panel/lib/LineMessageView.js:51:23)
    at HTMLPreElement.<anonymous> (/home/victor/.atom/packages/jsonlint/node_modules/atom-message-panel/node_modules/space-pen/lib/space-pen.js:214:36)
    at HTMLPreElement.jQuery.event.dispatch (/home/victor/.atom/packages/jsonlint/node_modules/atom-message-panel/node_modules/space-pen/vendor/jquery.js:4676:9)
    at HTMLPreElement.elemData.handle (/home/victor/.atom/packages/jsonlint/node_modules/atom-message-panel/node_modules/space-pen/vendor/jquery.js:4360:28)
```
### Commands

```
     -0:24.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:24.4.0 core:move-right (atom-text-editor.editor.is-focused)
 14x -0:24.1.0 core:move-down (atom-text-editor.editor.is-focused)
  4x -0:22.9.0 core:move-up (atom-text-editor.editor.is-focused)
 42x -0:22.1.0 core:select-down (atom-text-editor.editor.is-focused)
  3x -0:19.5.0 core:select-up (atom-text-editor.editor.is-focused)
     -0:18.8.0 core:delete (atom-text-editor.editor.is-focused)
  6x -0:18 core:move-down (atom-text-editor.editor.is-focused)
 38x -0:16.6.0 core:select-down (atom-text-editor.editor.is-focused)
 28x -0:12 core:select-up (atom-text-editor.editor.is-focused)
     -0:10.2.0 core:delete (atom-text-editor.editor.is-focused)
 11x -0:09.9.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:08.4.0 core:select-down (atom-text-editor.editor.is-focused)
     -0:07.9.0 core:select-to-bottom (atom-text-editor.editor.is-focused)
     -0:07.4.0 core:select-up (atom-text-editor.editor.is-focused)
     -0:04.2.0 core:delete (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "seti-ui",
      "one-dark-syntax"
    ],
    "autoHideMenuBar": true,
    "disabledPackages": [
      "linter-jsonlint"
    ]
  },
  "jsonlint": {
    "validateOnChange": true,
    "hideOnNoErrors": true
  }
}
```
### Installed Packages

``` coffee
# User
jsonlint, v1.1.2
linter, v1.11.2
minimap, v4.16.1
seti-ui, v0.8.1

# Dev
No dev packages
```

**Comment by tcarlsen** [comment]
should be fixed in `v1.1.3`
